// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqdjhiousubwdlbptynl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZGpoaW91c3Vid2RsYnB0eW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzE2NTQsImV4cCI6MjA3NDM0NzY1NH0.m1YtTAWymKuTYizntYsos7Lm6NoZK8lVFkuYzBKGZUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});